name: test_minpro_newsfeed
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:

  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2

  flutter:
    sdk: flutter

  flutter_dotenv: ^5.0.2
  http: ^0.13.6
  json_annotation: ^4.8.1
  provider: ^6.0.5

dev_dependencies:

  build_runner: ^2.4.4

  flutter_lints: ^2.0.0

  flutter_test:
    sdk: flutter

  json_serializable: ^6.6.2

flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/images/
