name: test_minpro_newsfeed
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:

  auto_size_text: ^3.0.0
  cached_network_image: ^3.2.3
  cupertino_icons: ^1.0.2

  drift: ^2.8.0
  flutter:
    sdk: flutter

  flutter_dotenv: ^5.0.2
  http: ^0.13.6
  json_annotation: ^4.8.1
  path: ^1.8.3
  path_provider: ^2.0.15
  provider: ^6.0.5
  sqlite3_flutter_libs: ^0.5.15
  webview_flutter: ^4.2.0

dev_dependencies:

  build_runner: ^2.4.4

  drift_dev: ^2.8.1
  flutter_lints: ^2.0.0

  flutter_test:
    sdk: flutter

  json_serializable: ^6.6.2

flutter:

  uses-material-design: true

  assets:
    - .env
    - assets/images/
