name: test_minpro_newsfeed
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2

  provider: ^6.0.5
  flutter_dotenv: ^5.0.2
  http: ^0.13.6
  json_annotation: ^4.8.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

  build_runner: ^2.4.4
  json_serializable: ^6.6.2

flutter:

  uses-material-design: true

  assets:
    - .env
